### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by cgebe**

### CODE REVIEW

**Comment by pltrdy** [comment]
The problem with `log_level` is not how to dodge it, but why it happens. I mean, current `pyrouge` code has such a parameter (see: https://github.com/bheinzerling/pyrouge/blob/master/pyrouge/Rouge155.py#L74) therefore it must not be a problem.

I do not care that much about this param, it just shows that you are not running the expected pyrouge code.

**Comment by cgebe** [comment]
Could it be a version problem? Maybe, the wrong version gets fetched by pip.

Were there changes to this specific parameter?

**Comment by cgebe** [comment]
It occurred in the Docker build, so it should be nothing related to my system setup.

**Comment by pltrdy** [comment]
The pyrouge package is out of date on PyPI. The code I wrote actually rely on the very last code (i.e. master) that does not correspond to any release. 

I changed to requirements a suggested to install `pyrouge` from my own fork so there should not be version issues anymore.

https://github.com/pltrdy/files2rouge/commit/59ad4b0c1c1c0ce9bbf7ee5a757a733940816898

**Comment by cgebe** [comment]
Reverted the hotfix and updated the Dockerfile. There is a small typo `--U` should be `-U` in the README.

Thank you very much for resolving this issue! :)

**Comment by pltrdy** [comment]
Oh, I forgot to merge it.

**Pull request merged**
